services:
  golang:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker-compose.env
    depends_on:
      - mongo
    restart: unless-stopped
    

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    
volumes:
  mongo-data: